# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [2]:
# import numpy and pandas
import numpy as np
import pandas as pd
import scipy.stats as stats

# Challenge 1 - Independent Sample T-tests

In this challenge, we will be using the Pokemon dataset. Before applying statistical methods to this data, let's first examine the data.

To load the data, run the code below.

In [3]:
# Run this code:

pokemon = pd.read_csv('../pokemon.csv')

Let's start off by looking at the `head` function in the cell below.

In [4]:
# Your code here:

pokemon.head()

#                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49   
1  2                Ivysaur  Grass  Poison    405  60      62       63   
2  3               Venusaur  Grass  Poison    525  80      82       83   
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123   
4  4             Charmander   Fire     NaN    309  39      52       43   

   Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0       65       65     45           1      False  
1       80       80     60           1      False  
2      100      100     80           1      False  
3      122      120     80           1      False  
4       60       50     65           1      False

The first thing we would like to do is compare the legendary Pokemon to the regular Pokemon. To do this, we should examine the data further. What is the count of legendary vs. non legendary Pokemons?

In [5]:
# Your code here: 
pokemon['Legendary'].value_counts()

False    735
True      65
Name: Legendary, dtype: int64

In [6]:
pk1 = pokemon[pokemon['Legendary']==True]

le_pk = pk1['Total'].tolist()

pk2 = pokemon[pokemon['Legendary']==False]

nole_pk = pk2['Total'].tolist()

Compute the mean and standard deviation of the total points for both legendary and non-legendary Pokemon.

In [7]:
# Your code here:


mean_le = np.mean(le_pk)
std_le = np.std(le_pk)

mean_non_le = np.mean(nole_pk)
std_non_le = np.std(nole_pk)



The computation of the mean might give us a clue regarding how the statistical test may turn out; However, it certainly does not prove whether there is a significant difference between the two groups.

In the cell below, use the `ttest_ind` function in `scipy.stats` to compare the the total points for legendary and non-legendary Pokemon. Since we do not have any information about the population, assume the variances are not equal.

In [8]:
# Your code here:
lepk= stats.norm.rvs(loc=mean_le,scale=std_le,size=len(le_pk))
lepk

array([600.24133481, 641.44214014, 580.86466913, 598.96366241,
       657.59510374, 699.1876081 , 676.83955505, 544.21372569,
       685.02115179, 747.63237513, 602.12547386, 714.4744022 ,
       624.36389696, 552.65045825, 701.52171671, 672.4518105 ,
       657.13945239, 622.02430879, 654.35125945, 706.80568343,
       681.18869398, 651.27720022, 557.27127499, 814.75892365,
       651.83923812, 644.25821637, 653.83752868, 608.90031124,
       645.85211325, 533.32960549, 696.60214128, 701.80059938,
       726.45290962, 601.56053204, 600.79658216, 628.80621298,
       632.48976481, 684.94656814, 633.84236888, 699.53926081,
       594.6720432 , 643.12885698, 637.31639583, 575.69980861,
       703.3938841 , 722.3099998 , 589.66110859, 641.08812901,
       657.86860653, 640.45366147, 599.94870125, 647.10686755,
       665.71513712, 636.35547118, 646.61360628, 730.1875026 ,
       635.9189731 , 621.3926123 , 642.42630586, 533.73668573,
       662.73542566, 611.7415125 , 620.02830316, 663.44

In [9]:
nolepk=stats.norm.rvs(loc=mean_non_le,scale=std_non_le,size=len(nole_pk))

nolepk

array([433.01088285, 301.97571011, 389.4866946 , 308.58903519,
       481.31266725, 298.19612696, 488.07823807, 453.98168201,
       471.8280527 , 363.31942224, 366.93006743, 441.57888315,
       439.51055643, 490.47816979, 329.44296744, 385.6066613 ,
       363.30245651, 236.42092244, 396.98340275, 488.64014505,
       347.89862628, 532.39269638, 375.23562933, 608.00552435,
       334.0262576 , 614.18576979, 565.50766349, 573.55912378,
       359.24016295, 442.41479401, 508.88457171, 342.78205245,
       251.97450758, 520.04708831, 566.58360547, 341.8136332 ,
       491.32343527, 316.78079826, 300.42764206, 362.43858337,
       548.06318098, 481.31548147, 349.92984586, 422.39732151,
       474.06701679, 405.50370383, 552.82523401, 443.87776316,
       381.41818932, 527.96731962, 346.37054177, 451.64211002,
       400.65048975, 332.51738297, 445.56712454, 352.68245119,
       593.29403429, 348.95271364, 450.6144402 , 542.85315923,
       320.26377236, 442.47239872, 552.19574807, 283.70

In [10]:
stats.ttest_ind(lepk,nolepk, equal_var = False)

Ttest_indResult(statistic=29.930139870077895, pvalue=1.0060402202040687e-56)

What do you conclude from this test? Write your conclusions below.

In [11]:
# Your conclusions here:



How about we try to compare the different types of pokemon? In the cell below, list the types of Pokemon from column `Type 1` and the count of each type.

In [12]:
pokemon['Type 1'].value_counts()

Water       112
Normal       98
Grass        70
Bug          69
Psychic      57
Fire         52
Electric     44
Rock         44
Dragon       32
Ground       32
Ghost        32
Dark         31
Poison       28
Steel        27
Fighting     27
Ice          24
Fairy        17
Flying        4
Name: Type 1, dtype: int64

In [13]:
# Your code here:
type_water=pokemon[pokemon['Type 1']== 'Water']
type_water

#                     Name Type 1 Type 2  Total  HP  Attack  Defense  \
9      7                 Squirtle  Water    NaN    314  44      48       65   
10     8                Wartortle  Water    NaN    405  59      63       80   
11     9                Blastoise  Water    NaN    530  79      83      100   
12     9  BlastoiseMega Blastoise  Water    NaN    630  79     103      120   
59    54                  Psyduck  Water    NaN    320  50      52       48   
..   ...                      ...    ...    ...    ...  ..     ...      ...   
724  656                  Froakie  Water    NaN    314  41      56       40   
725  657                Frogadier  Water    NaN    405  54      63       52   
726  658                 Greninja  Water   Dark    530  72      95       67   
762  692                Clauncher  Water    NaN    330  50      53       62   
763  693                Clawitzer  Water    NaN    500  71      73       88   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
9         50       64     43           1      False  
10        65       80     58           1      False  
11        85      105     78           1      False  
12       135      115     78           1      False  
59        65       50     55           1      False  
..       ...      ...    ...         ...        ...  
724       62       44     71           6      False  
725       83       56     97           6      False  
726      103       71    122           6      False  
762       58       63     44           6      False  
763      120       89     59           6      False  

[112 rows x 13 columns]

In [14]:
water = type_water['Total']
water = water.tolist()

water

[314,
 405,
 530,
 630,
 320,
 500,
 300,
 385,
 510,
 335,
 515,
 315,
 490,
 590,
 325,
 475,
 305,
 525,
 325,
 475,
 295,
 440,
 320,
 450,
 340,
 520,
 200,
 540,
 640,
 535,
 525,
 314,
 405,
 530,
 330,
 460,
 250,
 420,
 500,
 210,
 430,
 490,
 430,
 380,
 300,
 480,
 465,
 540,
 580,
 310,
 405,
 535,
 635,
 220,
 340,
 480,
 270,
 430,
 305,
 460,
 560,
 400,
 500,
 288,
 468,
 308,
 468,
 200,
 540,
 345,
 485,
 485,
 485,
 330,
 670,
 770,
 314,
 405,
 530,
 330,
 495,
 325,
 475,
 330,
 460,
 345,
 680,
 480,
 600,
 308,
 413,
 528,
 316,
 498,
 294,
 384,
 509,
 460,
 355,
 495,
 305,
 473,
 335,
 480,
 470,
 580,
 580,
 314,
 405,
 530,
 330,
 500]

In [15]:
type_others = pokemon[pokemon['Type 1'] != 'Water']

type_others

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[688 rows x 13 columns]

In [16]:
others = type_others['Total']

others = others.tolist()

others

[318,
 405,
 525,
 625,
 309,
 405,
 534,
 634,
 634,
 195,
 205,
 395,
 195,
 205,
 395,
 495,
 251,
 349,
 479,
 579,
 253,
 413,
 262,
 442,
 288,
 438,
 320,
 485,
 300,
 450,
 275,
 365,
 505,
 273,
 365,
 505,
 323,
 483,
 299,
 505,
 270,
 435,
 245,
 455,
 320,
 395,
 490,
 285,
 405,
 305,
 450,
 265,
 405,
 290,
 440,
 305,
 455,
 350,
 555,
 310,
 400,
 500,
 590,
 305,
 405,
 505,
 300,
 390,
 490,
 300,
 390,
 495,
 410,
 500,
 325,
 465,
 352,
 310,
 460,
 325,
 500,
 310,
 405,
 500,
 600,
 385,
 328,
 483,
 330,
 480,
 325,
 520,
 320,
 425,
 455,
 455,
 385,
 340,
 490,
 345,
 485,
 450,
 435,
 490,
 590,
 460,
 500,
 455,
 490,
 495,
 500,
 600,
 490,
 288,
 325,
 525,
 525,
 395,
 355,
 495,
 355,
 495,
 515,
 615,
 540,
 580,
 580,
 580,
 300,
 420,
 600,
 680,
 780,
 780,
 600,
 318,
 405,
 525,
 309,
 405,
 534,
 215,
 415,
 262,
 442,
 265,
 390,
 250,
 390,
 535,
 205,
 218,
 210,
 245,
 405,
 320,
 470,
 280,
 365,
 510,
 610,
 490,
 410,
 250,
 340,
 460,
 360

Since water is the largest group of Pokemon, compare the mean and standard deviation of water Pokemon to all other Pokemon.

In [17]:
# Your code here:

mean_water = np.mean(water)
mean_water

430.45535714285717

In [18]:
mean_others = np.mean(others)
mean_others

435.85901162790697

In [19]:
std_water = np.std(water)
std_water

112.681828329091

In [20]:
std_others = np.std(others)
std_others

121.00364762501172

Perform a hypothesis test comparing the mean of total points for water Pokemon to all non-water Pokemon. Assume the variances are equal. 

In [21]:
# Your code here:
from scipy.stats import ttest_1samp
pval = ttest_1samp(others, mean_water)

pval

Ttest_1sampResult(statistic=1.1704893818846211, pvalue=0.24220994453975542)

Write your conclusion below.

In [22]:
# Your conclusions here:


# Challenge 2 - Matched Pairs Test

In this challenge we will compare dependent samples of data describing our Pokemon. Our goal is to see whether there is a significant difference between each Pokemon's defense and attack scores. Our hypothesis is that the defense and attack scores are equal. In the cell below, import the `ttest_rel` function from `scipy.stats` and compare the two columns to see if there is a statistically significant difference between them.

In [23]:
pokemon

#                   Name   Type 1  Type 2  Total  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison    318  45      49       49   
1      2                Ivysaur    Grass  Poison    405  60      62       63   
2      3               Venusaur    Grass  Poison    525  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison    625  80     100      123   
4      4             Charmander     Fire     NaN    309  39      52       43   
..   ...                    ...      ...     ...    ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy    600  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy    700  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost    600  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark    680  80     160       60   
799  721              Volcanion     Fire   Water    600  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 13 columns]

In [24]:
# Your code here:
attack = pokemon['Attack'].tolist()

mean_a = np.mean(attack)
std_a= np.std(attack)

atk = stats.norm.rvs(loc=mean_a, scale=std_a, size=len(attack))

atk

array([111.68966701,  27.00622941,  58.33167328,  82.20351052,
        31.16516759, 104.73248776,  35.64816456, 123.7114871 ,
        39.24412495, 146.21727811,  72.64749954,  27.75089426,
       113.58092037,  86.19291832,  76.46186181, 120.88286935,
       110.15499798,  93.55396045,  86.99997565,  37.25212135,
        76.63807286,  68.49995057,  55.35258124,  17.82969273,
        90.89763074,  26.09187427,  83.28336407,  65.48553696,
        61.77735832, 124.03555172,  38.31482184, 100.32890602,
        98.2375251 , 121.23838159,  26.90869214,  98.15443302,
        81.82762546, 108.70701588,  62.83236072,  89.53239887,
       105.77699025, 147.65807955,  43.26251432, 136.20975625,
        98.68107662,  58.96481483,  63.90741462, 111.39171584,
        96.31258506, 111.28805277, 123.05902329,  71.04510769,
        62.86530461,  16.05806787,  69.39507473,  64.72551622,
       136.13507599,  99.3369272 ,  96.62728203, 112.07176748,
        99.98789661,  62.95537605,  74.96440822, 117.51

In [25]:
defense = pokemon ['Defense'].tolist()

mean_d = np.mean(defense)
std_d = np.std(defense)

dfs = stats.norm.rvs(loc=mean_d, scale=std_d, size=len(defense))

dfs

array([138.09767333, 106.23851417,  60.99455162,  87.64496779,
        98.05543905,  54.95887375, 119.19510729, 114.96785191,
        35.90112931,  80.64447067,  67.32928229,  63.03338418,
        44.60292971,  99.38293037, 127.80299734,  77.16668002,
        78.73235314,  37.02575552,  56.71865925,  65.08809682,
        89.33938981, 100.66293059,  75.98319467,  77.38722382,
        36.65135375,  98.04071835, 102.37489037,  56.807223  ,
        76.83314763,  76.67920308,  74.62878063,   4.85281032,
        64.50872038,  68.67744946,  64.42678137,  51.08634102,
       109.07922992,  75.51762108,  42.8581182 ,  75.42992552,
        63.99250488,  49.32373618, 100.28379432,  38.93558742,
        99.31806842, 100.72027575,  60.2867081 ,  79.34614525,
        81.06601008,  96.59281764,  25.26738518,  80.91870541,
        68.69605828,  46.28946612, 110.45254032, 116.25179442,
        81.78640358,  97.16946453,  44.45250904,  55.9144594 ,
       123.32625464,  23.91023147,  45.48083949,  80.66

In [26]:
stats.ttest_rel(atk,dfs)

Ttest_relResult(statistic=1.9460613158633708, pvalue=0.051997632814681866)

Describe the results of the test in the cell below.

In [27]:
# Your conclusions here:



We are also curious about whether therer is a significant difference between the mean of special defense and the mean of special attack. Perform the hypothesis test in the cell below. 

In [28]:
# Your code here:
sp_a = pokemon['Sp. Atk'].tolist()
mean_spa =np.mean(sp_a)

sp_d = pokemon['Sp. Def'].tolist()
mean_spd = np.mean(sp_d)




In [29]:
from scipy.stats import ttest_ind
ttest_ind(sp_a,sp_d)

Ttest_indResult(statistic=0.6041290031014401, pvalue=0.5458436328840358)

Describe the results of the test in the cell below.

In [30]:
# Your conclusions here:



As you may recall, a two sample matched pairs test can also be expressed as a one sample test of the difference between the two dependent columns.

Import the `ttest_1samp` function and perform a one sample t-test of the difference between defense and attack. Test the hypothesis that the difference between the means is zero. Confirm that the results of the test are the same.

In [43]:
# Your code here:
    
pokemon

attack = pokemon['Attack']

defense = pokemon['Defense']


test_a =  ttest_1samp(attack, 0 )
test_a

Ttest_1sampResult(statistic=68.84393492906322, pvalue=0.0)

In [42]:
test_b =  ttest_1samp(defense, 0 )
test_b 

Ttest_1sampResult(statistic=66.97712771588154, pvalue=0.0)

# Bonus Challenge - The Chi-Square Test

The Chi-Square test is used to determine whether there is a statistically significant difference in frequencies. In other words, we are testing whether there is a relationship between categorical variables or rather when the variables are independent. This test is an alternative to Fisher's exact test and is used in scenarios where sample sizes are larger. However, with a large enough sample size, both tests produce similar results. Read more about the Chi Squared test [here](https://en.wikipedia.org/wiki/Chi-squared_test).

In the cell below, create a contingency table using `pd.crosstab` comparing whether a Pokemon is legenadary or not and whether the Type 1 of a Pokemon is water or not.

In [32]:
# Your code here:



Perform a chi-squared test using the `chi2_contingency` function in `scipy.stats`. You can read the documentation of the function [here](https://docs.scipy.org/doc/scipy-0.15.1/reference/generated/scipy.stats.chi2_contingency.html).

In [33]:
# Your code here:



Based on a 95% confidence, should we reject the null hypothesis?

In [34]:
# Your answer here:

